apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandraset
spec:
  serviceName: cassandraservice
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra-container
        image: projectboseacr.azurecr.io/projectboseaks
        ports:
        # - containerPort: 9160
        #   name: cassandraport
        - containerPort: 9042
          name: cassandraqueryport
        volumeMounts:
        - name: cassandra-vol
          mountPath: /var/lib/cassandra
  volumeClaimTemplates:
  - metadata:
      name: cassandra-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
