apiVersion: batch/v1
kind: CronJob
metadata:
  name: cassandracron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: bloboutputstaging
              persistentVolumeClaim:
                claimName: pvc-blob-output-staging
          containers:
          - name: cassandracron
            volumeMounts:
            - name: bloboutputstaging
              mountPath: /mnt/blob/output
            image: projectboseacr.azurecr.io/projectboseaks
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - cqlsh cassandraset-0 9042 -u aksuser -p password123 --execute=copy azuredata.azurecost from '/mnt/blob/output/test.csv' with header = true
            - rm /mnt/blob/output/test.csv
          restartPolicy: OnFailure