apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cassandraservice
  name: cassandraservice
spec:
  clusterIP: None
  ports:
  - name: 9160-9160
    port: 9160
    protocol: TCP
    targetPort: 9160
  selector:
    app: cassandra
  type: ClusterIP
status:
  loadBalancer: {}