apiVersion: v1
kind: Service
metadata:
    name: "projectboseaks-9be3"
    labels:
        app: "projectboseaks-9be3"
spec:
    type: LoadBalancer
    ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
    selector:
        app: "projectboseaks-9be3"