apiVersion: v1
kind: Service
metadata:
    name: "projectboseaks-30eb"
    labels:
        app: "projectboseaks-30eb"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "projectboseaks-30eb"