apiVersion: v1
kind: Service
metadata:
    name: "levelservice"
    labels:
        app: "leveldeploy"

spec:
    type: LoadBalancer
    loadBalancerIP: 20.31.127.107
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "leveldeploy"