version: '3.1'
services:
    mysqldb:
        build:
            context: ./mysql/
            dockerfile: Dockerfile
        command: --default-authentication-plugin=mysql_native_password
        restart: always
    cassandradb:
        build:
            context: ./cassandra/
            dockerfile: Dockerfile
        restart: always