on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: projectboseacr.azurecr.io
        username: ${{ secrets.acr_projectboseacr_username }}
        password: ${{ secrets.acr_projectboseacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/db/cassandra" -f  "db/cassandra/Dockerfile" -t projectboseacr.azurecr.io/projectboseaks:${{ github.sha }} --label dockerfile-path=db/cassandra/Dockerfile
        docker push projectboseacr.azurecr.io/projectboseaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_projectboseaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep projectboseaksb4e0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace projectboseaksb4e0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: projectboseaksb4e0
        container-registry-url: projectboseacr.azurecr.io
        container-registry-username: ${{ secrets.acr_projectboseacr_username }}
        container-registry-password: ${{ secrets.acr_projectboseacr_password }}
        secret-name: projectboseadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: projectboseaksb4e0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          projectboseacr.azurecr.io/projectboseaks:${{ github.sha }}
        imagepullsecrets: |
          projectboseadockerauth
